site_name: Chatisマニュアル
use_directory_urls: false
nav:
- 画面説明:
    - スマホ: 'sp_view.md'
    - PCブラウザ: 'pc_view.md'
- メッセージ入力:
    - スマホ: 'sp_chat.md'
    - PCブラウザ: 'pc_chat.md'
- グループ作成:
    - スマホ: 'sp_group.md'
    - PCブラウザ: 'pc_group.md'
- プロフィール変更:
    - スマホ: 'sp_pro.md'
    - PCブラウザ: 'pc_pro.md'
- ユーザー作成/削除: 'user.md'
- お知らせ: 'notice.md'
- 安否確認: 'anpi.md'
- WEB給与連携: 'salary.md'
- PHR連携: 'phr.md'
- アカウント認証: 'sms.md'
- 管理者・権限: 'admin.md'
- よくある質問: 'index.md'
- その他:
    - プッシュ通知が届かない: 'push.md'
    - パスワード初期化: 'password.md'
    - QRコード初期化: 'ioscode.md'
    - 対応スマホOS: 'os.md'
    - インストール: 'install.md'
    - アップデート: 'update.md'
    - SMS機能が無い場合: 'nosms.md'
    - SMSが届かない場合: 'whysms.md'
    - 部会グループ管理: 'bukai.md'
theme:
  name: material
  language: 'ja'
extra:
  search:
    language: 'ja'
plugins:
  - search
  - git-revision-date-localized